name: Generate Sitemap

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.html'
      - 'people/**/*.html'
      - 'assets/pdf/*.pdf'
      - 'robots.txt'
      - '.github/workflows/sitemap.yml'
    paths-ignore:
      - 'sitemap.xml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate sitemap.xml
        shell: bash
        run: |
          set -u
          BASE_URL="https://furkanakosman.github.io/IPS"

          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          # HTML+PDF dosyaları; gizli klasörleri ve workflow klasörünü dışla
          find . -type f \( -name "*.html" -o -name "*.pdf" \) \
            ! -path "./.git/*" \
            ! -path "./.github/*" \
            ! -name "sitemap.xml" \
            -print0 \
          | sort -z \
          | while IFS= read -r -d '' file; do
              file="${file#./}"
              url="${BASE_URL}/${file}"
              # index.html → klasör URL'si
              url="${url%/index.html}"
              url="${url/index.html/}"
              echo "  <url><loc>${url}</loc></url>" >> sitemap.xml
            done

          echo '</urlset>' >> sitemap.xml

      - name: Commit and push (auto)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update sitemap [skip ci]"
          file_pattern: sitemap.xml
