name: Generate Sitemap

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate sitemap.xml
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
        echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
        find . -type f -name "*.html" ! -path "./assets/*" ! -path "./node_modules/*" | while read file; do
          url="https://furkanakosman.github.io/IPS/${file#./}"
          echo "  <url><loc>${url}</loc></url>" >> sitemap.xml
        done
        echo '</urlset>' >> sitemap.xml

    - name: Commit and push sitemap.xml
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add sitemap.xml
        git commit -m "Auto-update sitemap.xml" || echo "No changes to commit"
        git push
